source $HOME/.config/nvim/settings/vim-plug.vim
source $HOME/.config/nvim/settings/configs.vim
source $HOME/.config/nvim/settings/mapkeys.vim
source $HOME/.config/nvim/settings/plugins/nvim-tree.vim
source $HOME/.config/nvim/settings/plugins/coc.vim
source $HOME/.config/nvim/settings/plugins/rainbow-parentheses.vim
source $HOME/.config/nvim/settings/plugins/indent-line.vim
source $HOME/.config/nvim/settings/plugins/ale.vim
source $HOME/.config/nvim/settings/plugins/vim-airline.vim
